### ISSUE TITLE
Nan in h_k and b_k matrices

### ISSUE THREAD

**Issue by UcefMountacer** [zhuyifan1993/Direct_RGB-D_SLAM#2]
Hi @zhuyifan1993,

I tested the tool, it seems to work fine with the TUM dataset. However, when tested on my own, I found issues related to h_k matrix having Nan values, which raises an error in the _cholesky() function.

Can you please help me to solve this issue. 

Thanks

**Comment by UcefMountacer** [comment]
I should precise the issue...

The problem is about the h_k matrix not being positive definite, I tried with changing loop closure parameters, deceasing them has no effect. For the TUM dataset, the matrix is indeed NOT positive definite but becomes so after all the iterations.

For my dataset, I had around 5000 or more pairs (in loop closure npy file), but even with that the matrix is still not positive definite and the cholesky decomposition fails.

Is there any other parameters to play with other than the threshholds of the loop closure algorithm, those seems without effect as the number of loop closure does not have an effect (big or small) ?

Is it helpful to change this: `sigma_matrix = np.identity(6) * 1e6` ?

Can you please guide me on how you adjusted parameters for the TUM dataset ?

Thanks

**Comment by zhuyifan1993** [comment]
Hello,

Thank you for reaching out to me. 

- Regarding your description, if you want to test this algorithm on your own dataset, you should change the camera intrinsics first. 

- Then you can try the pose graph optimization algorithm with some manually selected pairs as loop closure before you run it on the automatically generated pair list. 

- If the Hessian matrix has some abnormal entries, you can try to examine the intermedium results, e.g. residual, Jacobian. Also can try to use Gauss-Newton solver instead of Levenberg Marquardt for debugging.

Hope these suggestions could help you a bit.

**Comment by UcefMountacer** [comment]
**[EDITED]**

Hi, Thanks for your prompt response.

I have indeed changed the parameters. Thanks.

For the manuall PGO, how does it work ? is it just a different approach that I can 'simply' run or should I select manually the loops. Sorry I'm a bit confused.

_Also, for the Gauss Newton solver, does it work for non positive definite matrix ?_ 

Let me re-phrase, they are completely different approaches, however, I suggest to use np.linalg.pinv instead of np.linalg.inv as there are cases when the mmatrix is not inversible.

I'll keep this issue posted with updates.

Cheers

**Comment by UcefMountacer** [comment]
@zhuyifan1993 this problem was not solved sadly. The code gave me a hard time to try and debug where the problem comes from.

I tried for a whole week to change the solver between cholesky and Gauss Newton, I also played with a combination of loop closure pairs, keyframe thresholds, keyframe selection strategy. It seems as this code was written and made custom for a dataset like TUM vision. I used on the other hand lidar / rgb data from the iPhone.
